### ISSUE TITLE
怎么添加子集菜单信息？

### ISSUE THREAD

**Issue by chengqinghuanyu** [codedefault/tsadmin#1]
在menu.js中添加了一个自元素发现不能正常使用：
        children: [
            {
                title:'子页面',
                name:'子页面',
                path:'/mypage',
                uniqueNo:'mypage'
            }
        ]

我是在view目录下面新建了一个mypage.vue的页面；
点击子页面时发现提示：
The Tab [/mypage] is not defined!
不知道如何处理？

**Comment by lampo1024** [comment]
@chengqinghuanyu 需要在配置文件：frontend/tsadmin/app/config/tabs.js中添加你新建页面的配置
